apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-04tv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-04tv@sha256:c6276b2644edd7a14996abc98e3bfc61831a3767fdf20bfeb48ff8f7c3d4bb82
        name: my-nodejs
        resources: {}
status: {}
